name: flutter_opencc_ffi_android
description: Android platform implementation of flutter_opencc_ffi
repository: https://github.com/old-cookie/flutter_opencc_ffi/tree/master/flutter_opencc_ffi_android
issue_tracker: https://github.com/old-cookie/flutter_opencc_ffi/flutter_opencc_ffi/issues
version: 0.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: flutter_opencc_ffi
    platforms:
      android:
        package: com.whaleread.flutter_opencc_ffi.flutter_opencc_ffi
        pluginClass: FlutterOpenccFfiPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_opencc_ffi_platform_interface: ^0.0.3
#  flutter_opencc_ffi_platform_interface:
#    path: ../flutter_opencc_ffi_platform_interface
  flutter_opencc_ffi_native: ^0.0.3
#  flutter_opencc_ffi_native:
#    path: ../flutter_opencc_ffi_native